[package]
name = "cargo-funnel"
version = "0.2.2"
authors = ["Tom Pridham <pridham.tom@gmail.com>"]
edition = "2018"
description = "cargo subcommand to reorganize and sort your Cargo.toml"
repository = "https://github.com/TomPridham/cargo-funnel"
readme = "README.md"
keywords = ["sort", "toml", "reorganize", "formatter"]
categories = ["development-tools::cargo-plugins"]
license = "MIT"

[dependencies]
cargo_metadata = "0.8.0"
clap = "2.33.0"
toml_edit = "0.1.5"

